name: lint

on:
  - push
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: dschep/install-poetry-action@v1.3
      - name: Install Dependencies
        run: poetry install
      - run: black --diff --check .
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: dschep/install-poetry-action@v1.3
      - name: Install dependencies
        run: poetry install
      - run: pylint --errors-only PROJECT_NAME tests
