name: lint

on:
  - push
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: dschep/install-poetry-action@v1.3
      - name: Install Dependencies
        run: poetry install
      - run: make lint-black
  poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: dschep/install-poetry-action@v1.3
      - run: make lint-poetry
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: dschep/install-poetry-action@v1.3
      - name: Install dependencies
        run: poetry install
      - run: make lint-pylint
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'Dockerfile'
      - name: Linting dev.Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'dev.Dockerfile'
      - name: Linting dev.lint.Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'dev.lint.Dockerfile'
  in-docker:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: make docker-lint
