name: test

on:
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: dschep/install-poetry-action@v1.3
      - name: Install dependencies
        run: poetry install
      - name: pytest
        run: |
          cd tests
          pytest -vv
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -f dev.Dockerfile -t mattgleich/profile_stack_dev
      - name: Running docker image
        run: docker run mattgleich/profile_stack_dev
